export enum ActionTypes {
    ARTIST_PAGE_RENAME = "artist_page_rename",
    ARTIST_PAGE_LOCK = "artist_page_lock",
    ARTIST_PAGE_UNLOCK = "artist_page_unlock",
    ARTIST_USER_LINKED = "artist_user_linked",
    ARTIST_USER_UNLINKED = "artist_user_unlinked",
    BLIP_DELETE = "blip_delete",
    BLIP_HIDE = "blip_hide",
    BLIP_UNHIDE = "blip_unhide",
    BLIP_UPDATE = "blip_update",
    COMMENT_DELETE = "comment_delete",
    COMMENT_HIDE = "comment_hide",
    COMMENT_UNHIDE = "comment_unhide",
    COMMENT_UPDATE = "comment_update",
    FORUM_CATEGORY_CREATE = "forum_category_create",
    FORUM_CATEGORY_DELETE = "forum_category_delete",
    FORUM_CATEGORY_UPDATE = "forum_category_update",
    FORUM_POST_DELETE = "forum_post_delete",
    FORUM_POST_HIDE = "forum_post_hide",
    FORUM_POST_UNHIDE = "forum_post_unhide",
    FORUM_POST_UPDATE = "forum_post_update",
    FORUM_TOPIC_DELETE = "forum_topic_delete",
    FORUM_TOPIC_HIDE = "forum_topic_hide",
    FORUM_TOPIC_UNHIDE = "forum_topic_unhide",
    FORUM_TOPIC_LOCK = "forum_topic_lock",
    FORUM_TOPIC_UNLOCK = "forum_topic_unlock",
    FORUM_TOPIC_STICK = "forum_topic_stick",
    FORUM_TOPIC_UNSTICK = "forum_topic_unstick",
    FORUM_TOPIC_UPDATE = "forum_topic_update",
    HELP_CREATE = "help_create",
    HELP_DELETE = "help_delete",
    HELP_UPDATE = "help_update",
    IP_BAN_CREATE = "ip_ban_create",
    IP_BAN_DELETE = "ip_ban_delete",
    MASCOT_CREATE = "mascot_create",
    MASCOT_DELETE = "mascot_delete",
    MASCOT_UPDATE = "mascot_update",
    POOL_DELETE = "pool_delete",
    REPORT_REASON_CREATE = "report_reason_create",
    REPORT_REASON_DELETE = "report_reason_delete",
    REPORT_REASON_UPDATE = "report_reason_update",
    SET_UPDATE = "set_update",
    SET_DELETE = "set_delete",
    SET_CHANGE_VISIBILITY = "set_change_visibility",
    TAG_ALIAS_CREATE = "tag_alias_create",
    TAG_ALIAS_APPROVE = "tag_alias_approve",
    TAG_ALIAS_DELETE = "tag_alias_delete",
    TAG_ALIAS_UPDATE = "tag_alias_update",
    TAG_IMPLICATION_CREATE = "tag_implication_create",
    TAG_IMPLICATION_APPROVE = "tag_implication_approve",
    TAG_IMPLICATION_DELETE = "tag_implication_delete",
    TAG_IMPLICATION_UPDATE = "tag_implication_update",
    TICKET_CLAIM = "ticket_claim",
    TICKET_UNCLAIM = "ticket_unclaim",
    TICKET_UPDATE = "ticket_update",
    UPLOAD_WHITELIST_CREATE = "upload_whitelist_create",
    UPLOAD_WHITELIST_UPDATE = "upload_whitelist_update",
    UPLOAD_WHITELIST_DELETE = "upload_whitelist_delete",
    USER_BLACKLIST_CHANGED = "user_blacklist_changed",
    USER_TEXT_CHANGE = "user_text_change",
    USER_UPLOAD_LIMIT_CHANGE = "user_upload_limit_change",
    USER_FLAGS_CHANGE = "user_flags_change",
    USER_LEVEL_CHANGE = "user_level_change",
    USER_NAME_CHANGE = "user_name_change",
    USER_DELETE = "user_delete",
    USER_BAN = "user_ban",
    USER_UNBAN = "user_unban",
    USER_FEEDBACK_CREATE = "user_feedback_create",
    USER_FEEDBACK_UPDATE = "user_feedback_update",
    USER_FEEDBACK_DELETE = "user_feedback_delete",
    WIKI_PAGE_RENAME = "wiki_page_rename",
    WIKI_PAGE_DELETE = "wiki_page_delete",
    WIKI_PAGE_LOCK = "wiki_page_lock",
    WIKI_PAGE_UNLOCK = "wiki_page_unlock",
    MASS_UPDATE = "mass_update",
    NUKE_TAG = "nuke_tag",
    TAKEDOWN_DELETE = "takedown_delete",
    TAKEDOWN_PROCESS = "takedown_process",
    CREATED_FLAG_REASON = "created_flag_reason",
    EDITED_FLAG_REASON = "edited_flag_reason",
    DELETED_FLAG_REASON = "deleted_flag_reason",
    BULK_REVERT = "bulk_revert",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_MOVE_FAVORITES = "post_move_favorites",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_DELETE = "post_delete",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_UNDELETE = "post_undelete",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_DESTROY = "post_destroy",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_RATING_LOCK = "post_rating_lock",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_UNAPPROVE = "post_unapprove",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_REPLACEMENT_ACCEPT = "post_replacement_accept",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_REPLACEMENT_REJECT = "post_replacement_reject",
    /** @deprecated This is a legacy action that has been replaces by post events. */
    POST_REPLACEMENT_DELETE = "post_replacement_delete",
    /** @deprecated This is a legacy action type that has been replaced with various more specific action types. */
    EDITED_USER = "edited_user",
    /** @deprecated This is a legacy action type that has been replaced by `user_text_change`. */
    CHANGED_USER_TEXT = "changed_user_text",
    /** @deprecated This is a legacy action type that has been replaced by `user_feedback_create`. */
    CREATED_POSITIVE_RECORD = "created_positive_record",
    /** @deprecated This is a legacy action type that has been replaced by `user_feedback_create`. */
    CREATED_NEGATIVE_RECORD = "created_negative_record",
    /** @deprecated This is a legacy action type that has been replaced by `user_feedback_create`. */
    CREATED_NEUTRAL_RECORD = "created_neutral_record",
}

export const LegacyActions = [
    ActionTypes.CREATED_NEGATIVE_RECORD,
    ActionTypes.CREATED_NEUTRAL_RECORD,
    ActionTypes.CREATED_POSITIVE_RECORD,
    ActionTypes.CHANGED_USER_TEXT
];
